version: "3.7"

services:
    frontend:
        build:
            dockerfile: ./frontend/prod.Dockerfile

    backend:
        build:
            dockerfile: ./backend/prod.Dockerfile

    nginx:
        build:
            args:
                - nginx_file=nginx/nginx.conf
        ports:
            - 80:80
